### ISSUE TITLE
模拟器下提供可不扫码建立与chrome通信的开关

### ISSUE THREAD

**Issue by fattydevelop** [weexteam/weex-devtool-iOS#1]
在使用模拟器进行开发调试的时候无法使用扫码功能，往往只能看到实现效果，无法使用chrome进行debug。
- 是否可以考虑在native请求js bundle的时候建立socket连接？
- 在url中设置开关的打开？

**Comment by MaryWu** [comment]
模拟器还不支持扫码功能。如果要在模拟器实现调试，需要稍微改下应用代码主动调用inspector API接口连接chrome（见ReadMe），然后就可以在chrome里inspect和debug了。

**Comment by yangshengtao** [comment]
由于devtool是debug时才依赖的，需要让也业务方来决定是否连接chrome，后续版本可以考虑在url中添加规则来判断是否模拟器主动链接chrome debug，需要业务方按照这个规则定义url。此issue会在开发时重新打开
