### ISSUE TITLE
iOS 顶部的weex MNT 如何关闭?

### ISSUE THREAD

**Issue by likenow** [weexteam/weex-devtool-iOS#19]

**Comment by emptywalker** [comment]
我也想知道怎么关闭 ， 可以给个答案吗？

**Comment by likenow** [comment]
@emptywalker WXDevtool 内部实现了运行时加载，改动源码不是好的方式，pod 安装时配置一下只允许debug 安装即可。如下：
`pod 'WXDevtool', '0.15.3', :configurations => ['Debug']`

**Comment by tuoxie007** [comment]
开发weex的人和开发iOS的并不是一波人
