### ISSUE TITLE
调试时候报错：Uncaught ReferenceError: weex is not defined

### ISSUE THREAD

**Issue by xiaohuapunk** [weexteam/weex-devtool-iOS#2]
升级最新版本后报错：`Uncaught ReferenceError: weex is not defined`

**Comment by yangshengtao** [comment]
升级weex-devtool至0.2.74

**Comment by xiaohuapunk** [comment]
升级了weex-devtool至0.2.74，但是问题依然存在:
Using WXDevtool (0.9.5)
Using WeexSDK (0.9.5.1)

**Comment by yangshengtao** [comment]
是运行playground中的demo报的错吗
