### ISSUE TITLE
no file WXImgLoaderProtocol.h

### ISSUE THREAD

**Issue by 343max** [weexteam/weex-devtool-iOS#5]
WXImgLoaderProtocol.h isn't part of any pots nor can I find it anywhere else.

**Comment by yangshengtao** [comment]
WXImgLoaderProtocol isn't a part of WXDevtool, WXImgLoaderProtocol.h is a protocal in WeexSDK, you should implement the protocol in your demo project

**Comment by 343max** [comment]
So your demo code doesn't run out of the box and I have to implement some classes first just to try out the example code and see if it does what it is supposed to do?
