### ISSUE TITLE
集成iOS编译报错

### ISSUE THREAD

**Issue by hayvane** [weexteam/weex-devtool-iOS#7]
使用github源码依赖的方式
报错如下： NSObject+WXRuntimePropertyDescriptor.m:50:127: Multiple methods named 'count' found with mismatched result, parameter type or attributes

![61b6b454-2468-49cd-9c41-165390ac21dc](https://cloud.githubusercontent.com/assets/2957483/25126219/207f14c6-2464-11e7-980c-74eca3c98dd6.png)

**Comment by yangshengtao** [comment]
ok，会尽快修复
